Repository namansharma3007/PollQ, pull requests merged in 2024-10, with the labels that each got.

#26 Add Poll, Vote, Admin Model
  backend-server/index.js
  backend-server/src/models/AdminModel.js
  backend-server/src/models/PollModel.js
  backend-server/src/models/VoteModel.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#34 fix:page not found issue fixed
  frontend-voting/src/App.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#40 #issue #21 | Enhance: PageNotFound component with styling and icon
  frontend-voting/package-lock.json
  frontend-voting/src/components/PageNotFound.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#32 Updated Readme to provide guidance on .env file
  README.md
Labels: bug, hacktoberfest, hacktoberfest-accepted

#45 Sidebar hiding problem solved and result page created
  frontend-voting/src/App.tsx
  frontend-voting/src/components/Sidebar.tsx
  frontend-voting/src/pages/Result.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#46 Solved errors in the Landing.tsx file and improved the sidebar
  frontend-voting/src/App.tsx
  frontend-voting/src/components/Sidebar.tsx
  frontend-voting/src/pages/Landing.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#49 Logo added
  .DS_Store
  backend-server/.DS_Store
  frontend-voting/public/complete-logo.jpeg
  frontend-voting/public/logo.png
  node_modules/.DS_Store
Labels: hacktoberfest, hacktoberfest-accepted
